on:
  push:
    tags:
      - v*

name: release

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Build and push
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # v1
        with:
          username: winterjung
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: winterjung/split
          tag_with_ref: true
